server.port=8080

# Database connection settings
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD} 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.root=INFO

#Liquibase changes
spring.liquibase.change-log=classpath:db/changelogs/changelog-master.xml
spring.liquibase.enabled=false
spring.liquibase.database-change-log-table=databasechangelog
spring.liquibase.database-change-log-lock-table=databasechangeloglock

# File size
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB


# Application info for version management
info.app.name=@project.name@
info.app.version=@project.version@
info.app.description=@project.description@


#management related configs
management.endpoints.web.exposure.include=health,info

management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST,OPTIONS,HEAD 
# Include HEAD as well for health/info
management.endpoints.web.cors.allowed-headers=*
management.endpoints.web.cors.allow-credentials=false
management.endpoints.web.cors.max-age=3600

#jwt configs, replace with env variables in production
jwt.secret=${JWT_SECRET}
jwt.expirationTime=86400000


# Ensure no handler found exceptions are thrown
spring.mvc.throw-exception-if-no-handler-found=true
spring.devtools.add-properties=false


tdkservice.baseURL=http://localhost:8080/tdkservice

